### PR TITLE
Added support for 2024.2.* IDEs.

### PR DESCRIPTION
**Pull request by thecodemonk**
Updated what I think will add support for the latest IDE versions. Built and tested in IntelliJ 2024.2.0.1.

### CODE REVIEW

**Comment by thecodemonk** [comment]
This should fix #61

**Comment by pmarti9** [comment]
https://github.com/jasonhulbert/jetbrains-trash-panda-theme/blob/9276dae3a70975893da0202ac89c730da80f605c/build.gradle#L28

i wonder if just removing the untilBuild.Set() method would fix it..

**Comment by jwgeller** [comment]
> https://github.com/jasonhulbert/jetbrains-trash-panda-theme/blob/9276dae3a70975893da0202ac89c730da80f605c/build.gradle#L28
> 
> i wonder if just removing the untilBuild.Set() method would fix it..

For what it's worth, I noticed that the top two free themes for JetBrains currently set this:

https://github.com/dracula/jetbrains/blob/589a2b5616ba31b8a36bf38935529ae868732881/build.gradle.kts#L100
https://github.com/one-dark/jetbrains-one-dark-theme/blob/4a0d3ab32cf0b2fc0f7d0dfa21006c8c79beaef2/build.gradle#L64

**Comment by thecodemonk** [comment]
I removed the line, compiled, and tried to install it and got an error that the plugin wasn't supported. 
I set it to 243.* and it installed fine. I also set it to *.* and that worked as well. 

The advantage of no max build is that it will always work as new versions are released.
The disadvantage is that if a new build has changes to the way themes work, it would leave the plugin in a broken state.

**Comment by jwgeller** [comment]
This appears to be addressed in #63

**Comment by jwgeller** [comment]
Perhaps #63 can be followed as a reference for now for future required updates.

**Comment by jasonhulbert** [comment]
Thanks @thecodemonk - and sorry again for the delay.

**Pull request closed without merging**
